# Generated by Django 5.0.4 on 2024-05-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_qrcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitcardorder',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
