# Generated by Django 5.0.4 on 2024-05-07 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1_qrcode', '0002_alter_visitcardorder_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitcardorder',
            name='post',
            field=models.CharField(default=datetime.datetime(2024, 5, 7, 6, 16, 44, 388474, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
