# Generated by Django 5.0.4 on 2024-05-07 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0002_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
