# Generated by Django 5.0.4 on 2024-05-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0005_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blog', to='app2_data.tag'),
        ),
    ]
