# Generated by Django 5.0.4 on 2024-05-08 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0008_question_book_des1_book_des2'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='book', to='app2_data.question'),
        ),
    ]
