# Generated by Django 5.0.4 on 2024-05-08 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0009_book_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='chapter',
            field=models.CharField(default=datetime.datetime(2024, 5, 8, 8, 44, 4, 188038, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
