# Generated by Django 5.0.4 on 2024-05-08 09:09

import app2_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0010_book_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('image', models.ImageField(upload_to='people_images/%Y/%m/%d')),
                ('post', models.TextField()),
                ('url', models.URLField(unique=True, validators=[app2_data.models.validate_linkedin_url])),
            ],
        ),
    ]
