# Generated by Django 5.0.4 on 2024-05-08 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0011_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='blog',
            field=models.TextField(default=datetime.datetime(2024, 5, 8, 9, 12, 28, 19302, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='post',
            field=models.CharField(max_length=25),
        ),
    ]
