# Generated by Django 5.0.4 on 2024-05-08 09:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0012_person_blog_alter_person_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 8, 9, 28, 44, 235563, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
