# Generated by Django 5.0.4 on 2024-05-08 10:55

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0013_person_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qustion_title',
            new_name='question_title',
        ),
        migrations.RemoveField(
            model_name='book',
            name='des1',
        ),
        migrations.RemoveField(
            model_name='book',
            name='des2',
        ),
        migrations.RemoveField(
            model_name='book',
            name='question',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=datetime.datetime(2024, 5, 8, 10, 55, 35, 198481, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='books', to='app2_data.question'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='app2_data.category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='app2_data.tag'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(),
        ),
    ]
