# Generated by Django 5.0.4 on 2024-05-08 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0015_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
