# Generated by Django 5.0.4 on 2024-05-08 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0016_location_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='image',
            field=models.ImageField(default=datetime.datetime(2024, 5, 8, 14, 34, 46, 701435, tzinfo=datetime.timezone.utc), upload_to='location_images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
