# Generated by Django 5.0.4 on 2024-05-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0019_jobapplicationstep_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationstep',
            name='image',
            field=models.ImageField(upload_to='jobapplication_images/%Y/%m/%d'),
        ),
    ]
