# Generated by Django 5.0.4 on 2024-05-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0020_alter_jobapplicationstep_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('vacancy_des', models.TextField()),
                ('vacancy_requirements', models.TextField()),
                ('roles', models.TextField()),
                ('vacancy_skills', models.TextField()),
                ('vacancy_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Vacancies',
                'ordering': ['-post_date'],
            },
        ),
    ]
