# Generated by Django 5.0.4 on 2024-05-10 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0021_jobvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='bio',
            field=models.CharField(default=datetime.datetime(2024, 5, 10, 8, 29, 42, 768558, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
