# Generated by Django 5.0.4 on 2024-05-10 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0022_blog_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.CharField(default=datetime.datetime(2024, 5, 10, 9, 47, 16, 639319, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
