# Generated by Django 5.0.4 on 2024-05-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0024_casestudy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobVacancy',
            new_name='Job_Vacancy',
        ),
    ]
