# Generated by Django 5.0.4 on 2024-05-11 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_data', '0025_rename_jobvacancy_job_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 11, 16, 11, 0, 857183, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobapplicationstep',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 11, 16, 11, 3, 876185, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 5, 11, 16, 11, 5, 480183, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='Blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(upload_to='Book/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='casestudy',
            name='case_study_image',
            field=models.ImageField(upload_to='CaseStudy/'),
        ),
        migrations.AlterField(
            model_name='jobapplicationstep',
            name='image',
            field=models.ImageField(upload_to='Jobapplicationstep/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.ImageField(upload_to='Location/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(upload_to='Person/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
