# Generated by Django 5.0.4 on 2024-05-08 12:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('project_description', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('engagement_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3_user.engagementchoice')),
                ('services_needed', models.ManyToManyField(to='app3_user.service')),
            ],
            options={
                'ordering': ['-post_date'],
            },
        ),
    ]
