# Generated by Django 5.0.4 on 2024-05-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3_user', '0004_contactformsubmission_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='country',
            field=models.CharField(choices=[('nepal', 'Nepal'), ('india', 'India'), ('usa', 'USA')], default='nepal'),
        ),
    ]
